# compose syntax version.
version: "3.6"

# services declaration.
services:
  # golang
  app:
    build: 
      context: ./
    image: hillushilbert/fullcycle-d1-golang
    container_name: golang
    volumes:
      - ./src:/go/src/app

